yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from django.urls import include
from . import views
app_name = 'posts'

urlpatterns = [
    path('',  views.index, name = 'índex'),
    path('group_posts/<str:name>/', views.group_posts, name = 'group_post'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('group/<slug:slug>/', include('posts.urls'))
]

yatube/yatube_project/yatube_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models

# Create your models here.

yatube/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    template = 'posts/index.html'
    text = 'Это главная страница проекта Yatube'
    context = {
        'text': text,
    }
    return render(request, template, context)


def group_posts(request):
    template = 'posts/group_list.html'
    text = 'Здесь будет информация о группах проекта Yatube'
    context = {
        'text': text,
    }
    return render(request, template, context)

# Create your views here.

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Не найдено{% endblock %}</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      {% include 'íncludes/header.html' %}
    </header>
    <main> 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">    
        {% block content %}Не найдено{% endblock %}
        <!-- под последним постом нет линии -->
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      {% include 'íncludes/footer.html' %}   
    </footer>
  </body>

yatube/templates/includes/footer.html
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>     

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ text }}{% endblock %}
{% block content %}
<h1>Лев Толстой – зеркало русской революции.</h1>
<p>
  Группа тайных поклонников графа.
</p>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 30 июля 1854
    </li>
  </ul>      
  <p>
    [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
    Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
    Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
    къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
    и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
    ебѣ за нынѣшній день. (3)
  </p>         
</article>
<hr>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 29 июля 1854
    </li>
  </ul> 
  <p>
    Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
    съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
    что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
    веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
    отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
    — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
    Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
    чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
    накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
    безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
  </p>      
</article>
<hr>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 28 июля 1854
    </li>
  </ul> 
  <p>
    Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
    Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
    Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
    хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
    Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
    днемъ своимъ очень доволенъ. (1)
  </p>
</article>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ text }}{% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 30 июля 1854
    </li>
  </ul>      
  <p>
    [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
    Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
    Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
    къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
    и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
    ебѣ за нынѣшній день. (3)
  </p>
  <a href="{% url 'posts:group_post' %}">все записи группы</a>
</article>
<hr>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 29 июля 1854
    </li>
  </ul> 
  <p>
    Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
    съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
    что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
    веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
    отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
    — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
    Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
    чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
    накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
    безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
  </p>
  <a href="{% url 'posts:group_post' %}">все записи группы</a>
</article>
<hr>
<article>
  <ul>
    <li>
      Автор: Лев Толстой
    </li>
    <li>
      Дата публикации: 28 июля 1854
    </li>
  </ul> 
  <p>
    Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
    Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
    Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
    хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
    Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
    днемъ своимъ очень доволенъ. (1)
  </p>
  <a href="{% url 'posts:group_post' %}">все записи группы</a>
</article>
{% endblock %}